### PR TITLE
fix: Use correct `format` when resolving exports from sub-modules

### LINKED ISSUE #139: Errors when importing vue/server-renderer
The `vue/server-renderer` export in the vue package re-exports `@vue/server-renderer`.  

## Expected Behavior

Applications which import `vue/server-renderer` will work fine when the `import-in-the-middle` hook is loaded.

## Actual Behavior

When attempting to open the application, the following error is logged:

```
[nuxt] [request error] [unhandled] [500] The requested module 'vue/server-renderer' does not provide an export named 'renderToString'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:131:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:213:5)
  at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
  at async Object.handler (./.output/server/chunks/runtime.mjs:2861:19)
  at async Server.toNodeHandle (./.output/server/chunks/runtime.mjs:3131:7)
[nuxt] [request error] [unhandled] [500] The requested module 'vue/server-renderer' does not provide an export named 'renderToString'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:131:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:213:5)
  at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
  at async Object.handler (./.output/server/chunks/runtime.mjs:2861:19)
  at async Server.toNodeHandle (./.output/server/chunks/runtime.mjs:3131:7)
```

## Steps to Reproduce the Problem

  1. Create a basic Nuxt app `npx nuxi init test-app`
  2. Add `import-in-the-middle` `yarn add import-in-the-middle`
  3. Build `yarn nuxt build`
  4. Run with `import-in-the-middle` `node --loader=import-in-the-middle/hook.mjs .output/server/index.mjs`

Alternatively, this single-file approach seems to recreate the problem

**index.mjs**
```
import { renderToString } from 'vue/server-renderer'

console.log('hello world')
```

```
❯ node index.mjs
hello world
❯ node --loader=import-in-the-middle/hook.mjs index.mjs
(node:75208) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("import-in-the-middle/hook.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
file:///private/tmp/import-test/index.mjs:1
import { renderToString } from 'vue/server-renderer'
         ^^^^^^^^^^^^^^
SyntaxError: The requested module 'vue/server-renderer' does not provide an export named 'renderToString'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:131:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:213:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.9.0
```

## Specifications

  - Version: 1.9.0 (Node v20.9.0)
  - Platform: MacOS
  - Subsystem:

### PR DESCRIPTION
**Pull request by timfish**
Closes #139

When we resolve sub-modules to get their exports, `parentResolve` can return a different `format` to the current module type and this should be used when loading the module source!

This change is potnetially a one-liner but I refactored the code a bit to avoid initially setting `let` variables as undefined only to set them later in an if/else.

### CODE REVIEW

File: test/hook/vue-server-renderer.mjs [hunk 1]
```diff
@@ -0,0 +1,4 @@
+import { strictEqual } from 'assert'
```
Comment (jsumners-nr) [inline test/hook/vue-server-renderer.mjs:1]: What do you think about adding a leading comment that describes the purpose of/reason for this test?

Comment (timfish) [reply test/hook/vue-server-renderer.mjs:1]: Maybe just link to #139?

Comment (jsumners-nr) [reply test/hook/vue-server-renderer.mjs:1]: That would at least be easier than needing to navigate `git blame`.

**Review by jsumners-nr — APPROVED** [review]

**Review by AbhiPrasad — APPROVED** [review]
the differing formats is really tricky, something we need to keep an eye on for the future.
